job/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('',index,name="index"),
    path('select-user/', select_user, name="select-user"),
    path('admin_login',admin_login,name="admin_login"),
    path('user_login',user_login,name="user_login"),
    path('recruiter_signup',recruiter_signup,name="recruiter_signup"),
    path('recruiter_login',recruiter_login,name="recruiter_login"),
    path('logout-user',logoutuser,name="logout-user"),
    path('user_signup',user_signup,name="user_signup"),
    path('user_home',user_home,name="user_home"),
    path('Logout',Logout,name="Logout"),

]

jobportal/urls.py
from django.contrib import admin
from django.urls import path, include
from job.views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('job.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.


class User(AbstractUser):
    email = models.EmailField(unique=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

class StudentUser(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    mobile = PhoneNumberField(max_length=15, null=False)
    image = models.ImageField(null=True)
    gender = models.CharField(max_length=10, null=True)
    type = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self):
        return self.user.username



class Recruiter(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    mobile = PhoneNumberField(max_length=15, null=False)
    image = models.ImageField(null=True)
    gender = models.CharField(max_length=10, null=True)
    company = models.CharField(max_length=100, null=True)
    type = models.CharField(max_length=10, null=True, blank=True)


    def __str__(self):
        return self.user.username

job/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from . models import *

GENDER_CHOICE = [
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Others', 'Others'),
]


class CreateUser(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'is_active']


class StudentCreate(ModelForm):
    gender = forms.ChoiceField(choices=GENDER_CHOICE, widget=forms.RadioSelect)
    class Meta:
        model = StudentUser
        fields = '__all__'


class RecuriterCreate(ModelForm):
    gender = forms.ChoiceField(choices=GENDER_CHOICE, widget=forms.RadioSelect)

    class Meta:
        model = Recruiter
        fields = '__all__'

job/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from.models import *
from.forms import *

# Create your views here.

def index(request):
    return render(request,'index.html')

def admin_login(request):
    return render(request,'admin_login.html')

def user_login(request):
    if request.user.is_authenticated:

        return redirect('/')

    if request.method == 'POST':
        email = request.POST.get('email').lower()
        password = request.POST.get('password')



        try:
            user = User.objects.get(email=email)
        except:
            messages.error(request, 'Email or Password Does Not Matched')

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('user_home')

    return render(request,'user_login.html')


def Logout(request):
    logout(request)
    return redirect('index')

def recruiter_login(request):
    return render(request,'recruiter_login.html')

def user_home(request):
    if not request.user.is_authenticated:
        return redirect('user_login')
    return render(request,'user_home.html')

def user_signup(request):
    if request.user.is_authenticated:
        return redirect('/')

    usercreate = CreateUser()
    stucreate = StudentCreate()
    if request.method == 'POST':
        usercreate = CreateUser(request.POST, request.FILES)
        stucreate = StudentCreate(request.POST, request.FILES)
        if usercreate.is_valid() & stucreate.is_valid():
            user = usercreate.save()
            stucreate = stucreate.save(False)
            stucreate.user = user
            stucreate.save()
            messages.success(request, 'User account was created!')
            return redirect('user_login')

        else:
            messages.error(request, 'An error has occurred during registration')

    context = {'usercreate':usercreate, 'stucreate':stucreate}
    return render(request,'user_signup.html', context)

def select_user(request):
    return render(request, 'select_user.html')

def recruiter_signup(request):
    if request.user.is_authenticated:
        return redirect('/')

    usercreate = CreateUser()
    reqcreate = RecuriterCreate()
    if request.method == 'POST':
        usercreate = CreateUser(request.POST, request.FILES)
        reqcreate = RecuriterCreate(request.POST, request.FILES)
        if usercreate.is_valid() & reqcreate.is_valid():
            user = usercreate.save()
            user.is_active = False
            reqcreate = reqcreate.save(False)
            reqcreate.user = user

            reqcreate.save()
        return redirect('user_login')
    context = {'usercreate':usercreate, 'reqcreate':reqcreate}
    return render(request, 'recruiter_signup.html', context)


def logoutuser(request):
    logout(request)
    return redirect('index')

job/templates/admin_login.html
{% load static %}

{% block body %}


{% include 'base.html' %}

<marquee style=" font-weight : bold ; font-family:'Monotype Corsiva' ; font-size :20px ; color:black ; background-color: #e33424 ; margin-top :.7% ">
    Admin Login
</marquee>
<hr>
<form class="container mt-5" method="post">
    {% csrf_token %}
    <label><b> UserName </b></label>
    <input type="text" class="form-control " name="uname" placeholder="Enter User Name">

     <label><b> Password </b></label>
    <input type="password" class="form-control " name="pwd" placeholder="Enter your password">

    <input type="submit" class="btn btn-primary " style="margin-top :1%">

</form>

{% endblock %}

job/templates/base.html
{% load static %}
<html>

<head>
    <title>Job Portal</title>
   <meta charset="utf-8">
  <meta name="viewport” contente="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<style>
    .nav-link{
    color: #2878d4 !important ;
    margin-right :4
    }


 .nav-link:hover {
  color: white !important ;
    font-weight : bold ;
    background-color : #3e82f0 ;
    border-radius : 20px;}

.navbar-brand:hover{
    color: #092cde !important ;

    }

</style>

</head>


<body>
{% include 'navigation.html' %}

{% block body %}
{% endblock %}



</body>


</html>

job/templates/footer.html
{% load static %}

<div class="mt-3" style="background-color :black ; width : 100% ; height:300px ;">
<div class="container">
    <div class="row">
        <div class="col-md-4 mt-3">
            <h3 class="text-white"> Contact Information </h3>
            <p style="color:yellow; font-size:18px"><i class="fa fa-map-marker" style="color:red;"></i> Uttara Sector 10, Dhaka-1230 </p>
            <p style="color:yellow; font-size:18px"><i class="fa fa-envelope" style="color:red;"></i>  sknayem945@gmail.com </p>
            <p style="color:yellow; font-size:18px"><i class="fa fa-phone" style="color:red;"></i> +8801765365583 </p>
            <p style="color:yellow; font-size:18px"><i class="fa fa-facebook" style="color:red;"></i> www.facebook.com/sk.nayem02 </p>

        </div>

        <div class="col-md-4 mt-3">
            <h3 class="text-white"> Online Placement</h3>
            <p style="color:yellow; font-size:18px">An employment website is a website that deals specially with
                employment or careers. Many employment websites are designed to
                allow employers to post job requirements for a position to be filled and
                are commonly known as job boards.</p>

        </div>

        <div class="col-md-4 mt-3">
            <h3 class="text-white"> News Letter</h3>
             <p style="color:yellow; font-size:18px">Keep up with our always upcoming news and updates. Enter your e-mail and subscribe to our newsletter.</p>



            <form method="post" class="form-inline">
                 <i class="fa fa-envelope " style=" margin-top:-5px;font-size:48px;color:#20aee6;"></i>
                {% csrf_token %}

                <input type="email" name="emailid" placeholder="Email Id" required class="form-control">
                <input type="submit" value="Subscribe" class="btn btn-primary">

            </form>


    </div>

</div>
<!--    <a href="#" id="ui-to-top" class="ui-to-top fa fa-angle-up active"></a>-->
</div>
</div>

job/templates/index.html
{% extends 'base.html' %}

{% load static %}


{% block body %}



<div class="container-fliud" style="margin-top:1%; margin-bottom:3%">
    <img src="{% static 'images/home2.jpg' %}" style="margin: -140px 0 0 65px;">


</div>



{% include 'footer.html' %}



{% endblock %}

job/templates/navigation.html
{% load static %}

<div class="container">
    <div class="row">
        <div class="col-sm-3 mt-2 ">
            <img src="{% static 'images/job1.1.jpg' %}" width="180px" height="80px">
        </div>

        <div class="col-sm-6 mt-5 text-center">
            <span style="font-weight : bold ; font-size: 30px">
                <span style="color: red ">Online Job </span>
                <span style="color: blue ">Portal System </span>
            </span>
        </div>

        <div class="col-sm-3 mt-5" style="padding-left:10%">
<span style="font-weight:bold ; font-size: 30px">
    <span><i class="fa fa-twitter pl-1"></i></span>
    <span><i class="fa fa-facebook pl-1"></i></span>
    <span><i class="fa fa-instagram pl-1"></i></span>
    <span><i class="fa fa-linkedin pl-1"></i></span>
</span>
        </div>
    </div>

</div>
<nav class="navbar navbar-expand-sm" style="background-color :#7cf3f7 ">
    {% if request.user.is_authenticated %}
        <a class=" navbar-brand  pl-5 font-weight-bold" style="font-family: cursive;"> <img src="{{ request.user.image.url }}"/>  Hello {{ request.user.username }} </a>
    {% else %}
        <a class=" navbar-brand  pl-5 font-weight-bold" style="font-family: cursive;"> Job Portal </a>
    {% endif %}

<ul class="navbar-nav">
    <li class=" nav-item">
        <a class=" nav-link font-weight-bold" href="{% url 'index' %}" style="margin-left:240px"><i class="fa fa-home mr-1"></i> Home </a>

    </li>

    <li class="nav-item">
        <a class="nav-link font-weight-bold" href="{% url 'index' %}  "><i class="fa fa-calendar-check-o mr-1"></i> Latest Jobs </a>

    </li>
     <li class="nav-item">
        <a class="nav-link font-weight-bold" href="{% url 'index' %}" > <i class="fa fa-address-book mr-1"></i> Contact </a>
    </li>

    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link font-weight-bold" href="{% url 'logout-user' %}" style="margin: 0 0 0 530px;" ><i class="fa fa-sign-out"></i> Logout </a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link font-weight-bold" href="{% url 'user_login' %}" ><i class="fa fa-user-plus mr-1"></i> User Login </a>
        </li>
        <li class="nav-item">
            <a class="nav-link font-weight-bold" href="{% url 'recruiter_login' %}" ><i class="fa fa-users mr-1"></i> Recruiter Login </a>
        </li>
        <li class="nav-item">
            <a class="nav-link font-weight-bold" href="{% url 'admin_login' %}" > <i class="fa fa-sign-in mr-1"></i> Admin Login </a>
        </li>
    {% endif %}


</ul>


</nav>


</body>
</html>

job/templates/recruiter_login.html
{% load static %}

{% block body %}


{% include 'base.html' %}

<marquee style=" font-weight : bold ; font-family:'Monotype Corsiva' ; font-size :20px ; color:black ; background-color: #e33424 ; margin-top :.7% ">
    Recruiter Login
</marquee>
<hr>
<form class="container mt-5 mb-5" method="post">
    {% csrf_token %}
    <label><b> Email ID </b></label>
    <input type="text" class="form-control " name="uname" placeholder="Enter you email">

     <label><b> Password </b></label>
    <input type="password" class="form-control " name="pwd" placeholder="Enter your password">

    <input type="submit" class="btn btn-primary " style="margin-top :1%">

    <a href="{% url 'recruiter_signup' %}" class="btn btn-primary " style="margin-top :1%"> SignUp</a>

</form>

{% include 'footer.html' %}

{% endblock %}

job/templates/recruiter_signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Your Job Account</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body style="background-color: #EEEEEE;">
    <style>
        #id_gender{
            display: inline-flex;
        }
        #id_gender_0, #id_gender_1, #id_gender_2{
            margin: 0 0 0 10px;
        }
        .size{
            display: inline-flex;
        }
        #id_phone{
            margin: 24px 0 0 0;
        }
    </style>
    <br>
    <br>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="">
                    <div class="row">
                    <div class="col">
                        <a href="{% url 'select-user' %}" class="btn btn-dark"><i class="fa-solid fa-circle-arrow-left">   back</i></a>
                    </div>
                    <br/>
                    <br/>
                    <br/>
                      <div class="card shadow-lg p-3 mb-5 bg-body rounded">
                          <div class="card-body">
                              <h3 style="text-align: center;">Job Holder's Registration Form</h3>
                              <br>
                              <form action="" method="POST" enctype="multipart/form-data">
                                  {% csrf_token %}
                                  <div class="row">
                                      <h5>Account Information</h5>
                                      <div class="col">
                                          {{ usercreate.first_name }}
                                      </div>
                                      <div class="col">
                                          {{ usercreate.last_name }}
                                      </div>
                                  </div>
                                  <br>
                                  <div class="row">
                                      <div class="col">
                                          {{ usercreate.username }}
                                      </div>
                                      <div class="col">
                                          {{ usercreate.email }}
                                      </div>
                                  </div>
                                  <br>

                                  <div class="row">
                                      <div class="col">
                                          {{ reqcreate.company }}
                                      </div>
                                  </div>
                                  <br/>
                                  <div class="row">
                                      <div class="col">
                                           {{ usercreate.password1 }}
                                      </div>
                                      <div class="col">
                                          {{ usercreate.password2 }}
                                      </div>
                                  </div>
                                  <br/>
                                  <div class="row">
                                      <div class="col">
                                        {{ reqcreate.image }}
                                      </div>
                                      <div class="col-md-6" style="">
                                         {{ reqcreate.mobile }}
                                      </div>

                                  </div>
                                  <br>
                                  <div class="row">
                                      <div class="col">
                                          Selact Your Gender :  {{ reqcreate.gender }}
                                      </div>

                                  <br/>

                                  <br/>
                                  <div class="">
                                      <button class="btn btn-dark" type="submit" name="submit"><i class="fa-solid fa-circle-arrow-right">   Register</i></button>
                                  </div>
                              </form>
                          </div>
                      </div>
                </div>

            </div>
        </div>
    </div>

    <script>
        var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='First Name';
		form_fields[1].className='form-control';
		form_fields[2].placeholder='Last Name';
		form_fields[2].className='form-control';
		form_fields[3].placeholder='Username';
		form_fields[3].className='form-control';
		form_fields[4].placeholder='Email';
		form_fields[4].className='form-control';
		form_fields[5].placeholder='Company Name';
		form_fields[5].className='form-control';
		form_fields[6].placeholder='Password';
		form_fields[6].className='form-control';
		form_fields[7].placeholder='Confirm Password';
		form_fields[7].className='form-control';
		form_fields[8].className='form-control';
		form_fields[9].placeholder='(+Country Code) Type your phone Number';
		form_fields[9].className='form-control';


		var form_selects = document.getElementsByTagName('select')
		form_selects[0].className='form-control';

    </script>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
</body>
</html>

job/templates/user_home.html
{% load static %}
{% block body %}
{% include 'user_navigation.html' %}




{% endblock %}

job/templates/user_login.html
{% load static %}

{% block body %}


{% include 'base.html' %}


<marquee style=" font-weight : bold ; font-family:'Monotype Corsiva' ; font-size :20px ; color:black ; background-color: #e33424 ; margin-top :.7% ">
    User Login
</marquee>
<hr>
{% if messages %}
<ul class="messages" style="padding: 0 0 0 500px; color: red; font-weight : bold ;">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form class="container mt-5 mb-5" method="POST">
    {% csrf_token %}
    <label><b> Email </b></label>
    <input type="text" class="form-control " name="email" placeholder="Enter Your Email......">

     <label><b> Password </b></label>
    <input type="password" class="form-control " name="password" placeholder="Enter your password">

    <input type="submit" value="Login" class="btn btn-primary " style="margin-top :1%">

    <a href="{% url 'select-user' %}" class="btn btn-primary " style="margin-top :1%"> SignUp</a>

</form>

{% include 'footer.html' %}


{% endblock %}

job/templates/user_signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Your Job Account</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body style="background-color: #EEEEEE;">
    <style>
        #id_gender{
            display: inline-flex;
        }
        #id_gender_0, #id_gender_1, #id_gender_2{
            margin: 0 0 0 10px;
        }
        .size{
            display: inline-flex;
        }
        #id_phone{
            margin: 24px 0 0 0;
        }
    </style>
    <br>
    <br>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="">
                    <div class="row">
                    <div class="col">
                        <a href="{% url 'select-user' %}" class="btn btn-dark"><i class="fa-solid fa-circle-arrow-left">   back</i></a>
                    </div>
                    <br/>
                    <br/>
                    <br/>
                        {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                                    {{ message }}
                                </li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                      <div class="card shadow-lg p-3 mb-5 bg-body rounded">
                          <div class="card-body">
                              <h3 style="text-align: center;">Candidate's Registration Form</h3>
                              <br>
                              <form action="" method="POST" enctype="multipart/form-data">
                                  {% csrf_token %}
                                  <div class="row">
                                      <h5>Account Information</h5>
                                      <div class="col">
                                          {{ usercreate.first_name }}
                                      </div>
                                      <div class="col">
                                          {{ usercreate.last_name }}
                                      </div>
                                  </div>
                                  <br>
                                  <div class="row">
                                      <div class="col">
                                          {{ usercreate.username }}
                                          {{ usercreate.username.error }}
                                      </div>
                                      <div class="col">
                                          {{ usercreate.email }}
                                          {% for error in field.errors %}
                                            <p class="error">{{error}}</p>
                                          {% endfor %}
                                      </div>
                                  </div>
                                  <br/>
                                  <div class="row">
                                      <div class="col">
                                           {{ usercreate.password1 }}
                                          {% for error in field.errors %}
                                            <p class="error">{{error}}</p>
                                          {% endfor %}
                                      </div>
                                      <div class="col">
                                          {{ usercreate.password2 }}
                                          {% for error in field.errors %}
                                            <p class="error">{{error}}</p>
                                          {% endfor %}
                                      </div>
                                  </div>
                                  <br/>
                                  <div class="row">
                                      <div class="col">
                                        {{ stucreate.image }}
                                      </div>
                                      <div class="col-md-6" style="">
                                         {{ stucreate.mobile }}
                                          {% for error in field.errors %}
                                            <p class="error">{{error}}</p>
                                          {% endfor %}
                                      </div>

                                  </div>
                                  <br>
                                  <div class="row">
                                      <div class="col">
                                          Selact Your Gender :  {{ stucreate.gender }}
                                      </div>

                                  <br/>
                                  <br/>
                                  <div class="">
                                      <button class="btn btn-dark" type="submit" name="submit"><i class="fa-solid fa-circle-arrow-right">   Register</i></button>
                                  </div>
                              </form>
                          </div>
                      </div>
                </div>

            </div>
        </div>
    </div>

    <script>
        var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='First Name';
		form_fields[1].className='form-control';
		form_fields[2].placeholder='Last Name';
		form_fields[2].className='form-control';
		form_fields[3].placeholder='Username';
		form_fields[3].className='form-control';
		form_fields[4].placeholder='Email';
		form_fields[4].className='form-control';
		form_fields[5].placeholder='Password';
		form_fields[5].className='form-control';
		form_fields[6].placeholder='Confirm Password';
		form_fields[6].className='form-control';
		form_fields[7].className='form-control';
		form_fields[8].placeholder='(+Country Code) Type your phone Number';
		form_fields[8].className='form-control';


		var form_selects = document.getElementsByTagName('select')
		form_selects[0].className='form-control';

    </script>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
</body>
</html>